# === SCREEN ===
SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 820

# === PLAYER ===
PLAYER_SPEED = 3
PLAYER_CLIMB_SPEED = 3
PLAYER_JUMP_POWER = 6
PLAYER_SPAWN_X_OFFSET = 80  # spawns at SCREEN_WIDTH - this value (right side)
PLAYER_SPAWN_X_LEFT = 380   # left side spawn x position
PLAYER_SPAWN_Y_OFFSET = 60  # spawns at SCREEN_HEIGHT - this value

# === PHYSICS ===
GRAVITY = 0.8
PLAYER_GRAVITY = 0.3
MAX_FALL_SPEED = 12
BARRELS_ENABLED = True
BARREL_SPEED = 2
BARREL_INTERVAL_MIN = 150
BARREL_INTERVAL_MAX = 350

# === DQN NETWORK ===
STATE_DIM = 11
ACTION_DIM = 8
HIDDEN_LAYER_1 = 256
HIDDEN_LAYER_2 = 128

# === TRAINING ===
LEARNING_RATE = 0.0005
LR_MILESTONES = [200000, 400000, 600000]  # train steps where LR drops
LR_GAMMA = 0.5  # multiply LR by this at each milestone
GAMMA = 0.99
BATCH_SIZE = 64
MEMORY_SIZE = 200000
TARGET_UPDATE_FREQ = 1000
TRAIN_LOG_INTERVAL = 100

# === EXPLORATION ===
EPSILON_START = 1.0
EPSILON_MID = 0.05
EPSILON_MIN = 0.01
EPSILON_DECAY_STEPS_1 = 50000
EPSILON_DECAY_STEPS_2 = 300000

# === TRAINER ===
EPISODES = 20000
MAX_STEPS_PER_EPISODE = 50000
WANDB_LOG_INTERVAL = 100
WANDB_PROJECT = "donkey-kong-dqn"

# === REWARDS ===
REWARD_CLIMB_UP_MULTIPLIER = 0.25
REWARD_CLIMB_DOWN_MULTIPLIER = 0.3
REWARD_TOWARD_LADDER = 0.15
REWARD_AWAY_LADDER = 0.2
REWARD_TOWARD_PRINCESS = 0.15
REWARD_AWAY_PRINCESS = 0.2
REWARD_JUMP_IRRELEVANT = 0.5
REWARD_JUMP_CLOSE = 3.0
REWARD_JUMP_CLOSE_THRESHOLD = 40
REWARD_DEATH = -50.0
REWARD_BARREL_HIT = -10.0
REWARD_WIN = 50.0
REWARD_EXIT_LADDER = 2.0
REWARD_FALL_PENALTY = 50.0

# === GAME ===
INITIAL_LIVES = 1
MAX_BARREL_HITS = 10
BARREL_HIT_SCORE_PENALTY = 10
WIN_SCORE = 100
PLATFORM_SCORE = 100
