# === SCREEN ===
SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 820

# === PLAYER ===
PLAYER_SPEED = 3
PLAYER_CLIMB_SPEED = 3
PLAYER_JUMP_POWER = 10
PLAYER_SPAWN_X_OFFSET = 80  # spawns at SCREEN_WIDTH - this value
PLAYER_SPAWN_Y_OFFSET = 60  # spawns at SCREEN_HEIGHT - this value

# === PHYSICS ===
GRAVITY = 0.8
MAX_FALL_SPEED = 12
BARRELS_ENABLED = True
BARREL_SPEED = 2
BARREL_INTERVAL_MIN = 150
BARREL_INTERVAL_MAX = 350

# === DQN NETWORK ===
STATE_DIM = 11
ACTION_DIM = 8
HIDDEN_LAYER_1 = 128
HIDDEN_LAYER_2 = 128

# === TRAINING ===
LEARNING_RATE = 0.001
GAMMA = 0.99
BATCH_SIZE = 64
MEMORY_SIZE = 50000
TARGET_UPDATE_FREQ = 1000
TRAIN_LOG_INTERVAL = 100

# === EXPLORATION ===
EPSILON_START = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY_STEPS = 100000

# === TRAINER ===
EPISODES = 20000
MAX_STEPS_PER_EPISODE = 50000
WANDB_LOG_INTERVAL = 100
WANDB_PROJECT = "donkey-kong-dqn"

# === REWARDS ===
REWARD_CLIMB_UP_MULTIPLIER = 0.5
REWARD_TOWARD_LADDER = 0.3
REWARD_AWAY_LADDER = 0.4
REWARD_TOWARD_PRINCESS = 0.2
REWARD_JUMP_IRRELEVANT = 1.0
REWARD_JUMP_DISTANT = 0.5
REWARD_JUMP_CLOSE = 5.0
REWARD_JUMP_CLOSE_THRESHOLD = 50
REWARD_JUMP_DISTANT_THRESHOLD = 100
REWARD_NO_JUMP_PENALTY = 2.0
REWARD_IDLE = -0.2
REWARD_DEATH = -10.0
REWARD_WIN = 50.0
REWARD_ALIVE = -0.1
REWARD_GRAB_LADDER = 1.0
REWARD_EXIT_LADDER = 4.0
REWARD_HANG_THRESHOLD = 30
REWARD_HANG_PENALTY_PER_FRAME = 0.03

# === GAME ===
INITIAL_LIVES = 1
MAX_BARREL_HITS = 20
BARREL_HIT_SCORE_PENALTY = 10
WIN_SCORE = 100
PLATFORM_SCORE = 100
